/// Flutter icons MyFlutterApp
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Typicons, (c) Stephen Hutchings 2012
///         Author:    Stephen Hutchings
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://typicons.com/
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Elusive, Copyright (C) 2013 by Aristeides Stathopoulos
///         Author:    Aristeides Stathopoulos
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://aristeides.com/
/// * MFG Labs, Copyright (C) 2012 by Daniel Bruce
///         Author:    MFG Labs
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.mfglabs.com/
///
import 'package:flutter/widgets.dart';

class MyFlutterApp {
  MyFlutterApp._();

  static const _kFontFam = 'MyFlutterApp';
  //static const String _kFontPkg = null;

  static const IconData key = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData mail = IconData(0xe801, fontFamily: _kFontFam);
  static const IconData home = IconData(0xe802, fontFamily: _kFontFam);
  static const IconData home_outline = IconData(0xe803, fontFamily: _kFontFam);
  static const IconData shopping_cart = IconData(0xe804, fontFamily: _kFontFam);
  static const IconData heart_empty = IconData(0xe805, fontFamily: _kFontFam);
  static const IconData heart_circled = IconData(0xe806, fontFamily: _kFontFam);
  static const IconData heart = IconData(0xe807, fontFamily: _kFontFam);
  static const IconData right_open = IconData(0xf006, fontFamily: _kFontFam);
  static const IconData left_open = IconData(0xf007, fontFamily: _kFontFam);
  static const IconData th_thumb = IconData(0xf00a, fontFamily: _kFontFam);
}
