/// Flutter icons MyFlutterApp
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
/// * Typicons, (c) Stephen Hutchings 2012
///         Author:    Stephen Hutchings
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://typicons.com/
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Elusive, Copyright (C) 2013 by Aristeides Stathopoulos
///         Author:    Aristeides Stathopoulos
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://aristeides.com/
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
/// * MFG Labs, Copyright (C) 2012 by Daniel Bruce
///         Author:    MFG Labs
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.mfglabs.com/
///
import 'package:flutter/widgets.dart';

class MyFlutterApp {
  MyFlutterApp._();

  static const _kFontFam = 'MyFlutterApp';

  static const IconData key = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData cancel = IconData(0xe801, fontFamily: _kFontFam);
  static const IconData logout = IconData(0xe802, fontFamily: _kFontFam);
  static const IconData heart = IconData(0xe803, fontFamily: _kFontFam);
  static const IconData basket = IconData(0xe804, fontFamily: _kFontFam);
  static const IconData mail_1 = IconData(0xe805, fontFamily: _kFontFam);
  static const IconData heart_empty = IconData(0xe806, fontFamily: _kFontFam);
  static const IconData location = IconData(0xe807, fontFamily: _kFontFam);
  static const IconData right_open = IconData(0xf006, fontFamily: _kFontFam);
  static const IconData left_open = IconData(0xf007, fontFamily: _kFontFam);
  static const IconData facebook_2 = IconData(0xf052, fontFamily: _kFontFam);
  static const IconData gplus = IconData(0xf0d5, fontFamily: _kFontFam);
  static const IconData google = IconData(0xf1a0, fontFamily: _kFontFam);
}
